### ISSUE TITLE
Wsdl2Gosu.fetch(URL, FILE) throws exceptions

### ISSUE THREAD

**Issue by vqminh** [gosu-lang/gosu-lang#12]
Wsdl2Gosu - Converting RPC style to Document style if necessary
Wsdl2Gosu - Done fetching schemas
Wsdl2Gosu - Writing results to .\src\main\resources\gw\ph\server
Wsdl2Gosu - Done writing results
gw.internal.gosu.parser.TypeRefException: Type interface changed.  Expected gw.internal.gosu.parser.IGosuClassInternal for main.java.gw.ph.FetchWsdls
	at gw.internal.gosu.parser.GosuProgram_Proxy.getReturnType(gw.internal.gosu.parser.GosuProgram_Proxy:1)
	at gw.lang.parser.ParseResult.getType(ParseResult.java:99)
	at gw.lang.Gosu$ExecuteMode.runWithFile(Gosu.java:769)
	at gw.lang.Gosu$ExecuteMode.run(Gosu.java:723)
	at gw.lang.Gosu.start(Gosu.java:123)
	at gw.lang.Gosu.main(Gosu.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.lang.ClassCastException: gw.internal.gosu.parser.JavaType cannot be cast to gw.lang.reflect.gs.IGosuProgram
	... 11 more

**Comment by lboasso** [comment]
deprecated/not supported

**Comment by Wanderish** [comment]
Hey, @vqminh I have a question.
Was Wsdl2Gosu.fetch() method something you wrote or was it something present in gosu?
