### ISSUE TITLE
BUG: using `thenComparing` in Gosu code

### ISSUE THREAD

**Issue by alchrabas** [gosu-lang/gosu-lang#120]
Hello,
I’m a Guidewire employee working on IS 10.
Some time ago we hit a strange bug in our Gosu code and we were finally able to find the cause.
The problem was caused by the use of `Comparator.thenComparing` method in a constructor of our helper class instantiated in PCF. The additional trouble was that the problem was happening only when displaying that specific PCF for the first time after running the PolicyCenter. Later everything was working as expected.

The fact that made it much harder to find the error was that when `thenComparing` was there, then putting a breakpoint inside of our class didn’t work. The code never got there.

I was a bit afraid the issue is caused by some special circumstances which are hard to reproduce, but fortunately the minimum test case is very simple. I was able to run it in Gosu Scratchpad and confirm it causes the exception: 

```
class A {
  construct() {
    var firstArray: String[] = {"a", "z", "keoq", "d", "c", "ad", "ce"}

    firstArray.sort(Comparator.comparingInt(\e -> e.hashCode()).thenComparing(Comparator.comparingInt(\a -> a.hashCode())))

    print(">>> " + firstArray)
  }
}

new A()
```

It results in the following exception:
```
java.lang.NullPointerException
	at gw.internal.gosu.parser.TypeLord._isRecursiveType(TypeLord.java:2300)
	at gw.internal.gosu.parser.TypeLord.isRecursiveType(TypeLord.java:2290)
	at gw.internal.gosu.parser.TypeLord.replaceTypeVariableTypeParametersWithBoundingTypes(TypeLord.java:1315)
	at gw.internal.gosu.parser.TypeLord.replaceTypeVariableTypeParametersWithBoundingTypes(TypeLord.java:1356)
	at gw.internal.gosu.parser.TypeLoaderAccess.replaceTypeVariableTypeParametersWithBoundingTypes(TypeLoaderAccess.java:1503)
	at gw.lang.reflect.TypeSystem.replaceTypeVariableTypeParametersWithBoundingTypes(TypeSystem.java:935)
	at gw.lang.reflect.FunctionType.inferParameterizedTypeFromArgTypesAndContextType(FunctionType.java:585)
	at gw.internal.gosu.parser.GosuParser.inferFunction(GosuParser.java:15839)
	at gw.internal.gosu.parser.GosuParser.inferFunctionType(GosuParser.java:15762)
	at gw.internal.gosu.parser.GosuParser.parseArgumentList(GosuParser.java:7667)
	at gw.internal.gosu.parser.GosuParser.parseMethodMember(GosuParser.java:6748)
	at gw.internal.gosu.parser.GosuParser.parseMethodMember(GosuParser.java:6695)
	at gw.internal.gosu.parser.GosuParser.parseMemberAccess(GosuParser.java:6682)
	at gw.internal.gosu.parser.GosuParser.parseMemberAccess(GosuParser.java:6630)
	at gw.internal.gosu.parser.GosuParser._parseIndirectMemberAccess(GosuParser.java:5430)
	at gw.internal.gosu.parser.GosuParser.parseIndirectMemberAccess(GosuParser.java:5347)
	at gw.internal.gosu.parser.GosuParser.parseIndirectMemberAccess(GosuParser.java:5341)
	at gw.internal.gosu.parser.GosuParser.parsePrimaryExpression(GosuParser.java:2954)
	at gw.internal.gosu.parser.GosuParser._parseUnaryExpressionNotPlusMinus(GosuParser.java:2898)
	at gw.internal.gosu.parser.GosuParser.parseUnaryExpressionNotPlusMinus(GosuParser.java:2797)
	at gw.internal.gosu.parser.GosuParser.parseUnaryExpression(GosuParser.java:2778)
	at gw.internal.gosu.parser.GosuParser.parseTypeAsExpression(GosuParser.java:2654)
	at gw.internal.gosu.parser.GosuParser.parseMultiplicativeExpression(GosuParser.java:2607)
	at gw.internal.gosu.parser.GosuParser.parseAdditiveExpression(GosuParser.java:2547)
	at gw.internal.gosu.parser.GosuParser.parseBitshiftExpression(GosuParser.java:2448)
	at gw.internal.gosu.parser.GosuParser._parseIntervalExpression(GosuParser.java:2356)
	at gw.internal.gosu.parser.GosuParser.parseIntervalExpression(GosuParser.java:2349)
	at gw.internal.gosu.parser.GosuParser.parseRelationalExpression(GosuParser.java:2258)
	at gw.internal.gosu.parser.GosuParser.parseEqualityExpression(GosuParser.java:1957)
	at gw.internal.gosu.parser.GosuParser.parseBitwiseAndExpression(GosuParser.java:1901)
	at gw.internal.gosu.parser.GosuParser.parseBitwiseXorExpression(GosuParser.java:1833)
	at gw.internal.gosu.parser.GosuParser.parseBitwiseOrExpression(GosuParser.java:1721)
	at gw.internal.gosu.parser.GosuParser.parseConditionalAndExpression(GosuParser.java:1668)
	at gw.internal.gosu.parser.GosuParser.parseConditionalOrExpression(GosuParser.java:1609)
	at gw.internal.gosu.parser.GosuParser._parseConditionalExpression(GosuParser.java:1430)
	at gw.internal.gosu.parser.GosuParser.parseConditionalExpression(GosuParser.java:1422)
	at gw.internal.gosu.parser.GosuParser.parseExpressionNoVerify(GosuParser.java:1225)
	at gw.internal.gosu.parser.GosuParser.parseArgExpression(GosuParser.java:8179)
	at gw.internal.gosu.parser.GosuParser.parseArgumentList(GosuParser.java:7533)
	at gw.internal.gosu.parser.GosuParser.parseMethodMember(GosuParser.java:6748)
	at gw.internal.gosu.parser.GosuParser.parseMethodMember(GosuParser.java:6695)
	at gw.internal.gosu.parser.GosuParser.parseMemberAccess(GosuParser.java:6682)
	at gw.internal.gosu.parser.GosuParser.parseMemberAccess(GosuParser.java:6630)
	at gw.internal.gosu.parser.GosuParser._parseIndirectMemberAccess(GosuParser.java:5430)
	at gw.internal.gosu.parser.GosuParser.parseIndirectMemberAccess(GosuParser.java:5347)
	at gw.internal.gosu.parser.GosuParser.parseIndirectMemberAccess(GosuParser.java:5341)
	at gw.internal.gosu.parser.GosuParser.parsePrimaryExpression(GosuParser.java:2954)
	at gw.internal.gosu.parser.GosuParser.parseAssignmentOrMethodCall(GosuParser.java:12528)
	at gw.internal.gosu.parser.GosuParser._parseStatement(GosuParser.java:10158)
	at gw.internal.gosu.parser.GosuParser.parseStatement(GosuParser.java:9973)
	at gw.internal.gosu.parser.GosuParser.parseStatement(GosuParser.java:9941)
	at gw.internal.gosu.parser.GosuParser.parseStatementsAndDetectUnreachable(GosuParser.java:644)
	at gw.internal.gosu.parser.GosuClassParser.parseBaseConstructorDefinition(GosuClassParser.java:5010)
	at gw.internal.gosu.parser.GosuClassParser.parseClassMembers(GosuClassParser.java:3912)
	at gw.internal.gosu.parser.GosuClassParser.parseClassStatement(GosuClassParser.java:3663)
	at gw.internal.gosu.parser.GosuClassParser.parseDefinitions(GosuClassParser.java:423)
	at gw.internal.gosu.parser.GosuClassParser.parseInnerClassDefinition(GosuClassParser.java:4311)
	at gw.internal.gosu.parser.GosuClassParser.parseClassMembers(GosuClassParser.java:4059)
	at gw.internal.gosu.parser.GosuClassParser.parseClassStatement(GosuClassParser.java:3663)
	at gw.internal.gosu.parser.GosuClassParser.parseDefinitions(GosuClassParser.java:423)
	at gw.internal.gosu.parser.GosuClass.compileDefinitionsIfNeeded(GosuClass.java:1551)
	at gw.internal.gosu.parser.GosuClass.compileDefinitionsIfNeeded(GosuClass.java:1494)
	at gw.internal.gosu.parser.GosuClass.isValid(GosuClass.java:925)
	at gw.internal.gosu.parser.GosuProgram_Proxy.isValid(gw.internal.gosu.parser.GosuProgram_Proxy:2)
	at gw.internal.gosu.parser.GosuProgramParser.parseExpressionOrProgram(GosuProgramParser.java:229)
	at gw.lang.Gosu.runWithFile(Gosu.java:621)
	at gw.lang.Gosu.start(Gosu.java:140)
	at gw.lang.Gosu.main(Gosu.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:46)
```

And when I run the same code without the `.thenComparing` part, then the code completes successfully:

```
class A {
  construct() {
    var firstArray: String[] = {"a", "z", "keoq", "d", "c", "ad", "ce"}

    firstArray.sort(Comparator.comparingInt(\e -> e.hashCode()))

    print(">>> " + firstArray)
  }
}

new A()
```

```
>>> [Ljava.lang.String;@51c15508
```

I've created a new issue because I don't know what can be the cause and if it can be linked to any other issue.

**Comment by DPUkyle** [comment]
Thank you for reporting it. Something seems wrong with the type inference when chaining the static calls of Comparator.

Using Gosu 1.14.7-SNAPSHOT, I tried sorting using this syntax but it also fails:
`    firstArray.sortBy(\elt ->elt, Comparator.comparingInt(\a -> a.hashCode()).thenComparing(Comparator.comparingInt(\a -> a.hashCode())))
`

It probably won't be fixed this week, but we will investigate soon.

**Comment by DPUkyle** [comment]
Correction, only the first method is static: Comparator#comparingInt is a static method; Comparator#thenComparing is a default implementation method.

**Comment by DPUkyle** [comment]
@alchrabas I did not verify the results, but this seems to be an effective workaround for now:

`    firstArray.sort(Comparator.comparingInt(\e -> e.hashCode()).thenComparingInt(\a -> a.hashCode()))
`

**Comment by alchrabas** [comment]
Thanks for the help :)
