### ISSUE TITLE
(__VALUE_TO_SET as java.lang.String))    - ERROR PCF NULL POINTER

### ISSUE THREAD

**Issue by douglasrezende** [gosu-lang/gosu-lang#133]
Hi All,
I create new PCF, when execute and click Update Button to insert new record in database I get following message:
ERROR Displaying to the user an exception message that is not a UserDisplayableException
java.lang.NullPointerException
	at com.guidewire.commons.entity.type2.SimpleEntityPropertyAccessor.setValueDynamically(SimpleEntityPropertyAccessor.java:39)
	at com.guidewire.commons.entity.type2.EntityPropertyAccessorBase.setValue(EntityPropertyAccessorBase.java:50)
	at gw.internal.gosu.runtime.GosuRuntimeMethods.setProperty(GosuRuntimeMethods.java:119)
	at fragment_.pcffragment.CustomActivityScreenDV.TYPE.TYPE.TYPE_defaultSetter_16.evaluate(Unknown Source)
	at gw.internal.gosu.parser.fragments.GosuFragment.evaluate(GosuFragment.java:485) - (CustomActivity.Type = (__VALUE_TO_SET as java.lang.String))
	at com.guidewire.pl.system.expression.GosuFragmentExecutableFragment.evaluate(GosuFragmentExecutableFragment.java:26)
	at com.guidewire.pl.web.config.AnonymousMethod.handleCall(AnonymousMethod.java:260)
	at com.guidewire.pl.web.config.codegen.method.AbstractMethodCall.invoke(AbstractMethodCall.java:63)
	at com.guidewire.pl.web.value.ValueWidget.setModelValueToValueExpression(ValueWidget.java:280)
	at com.guidewire.pl.web.value.ValueWidget.setModelValue(ValueWidget.java:252)
	at com.guidewire.pl.web.value.ValueWidget.onUpdateModel_internal(ValueWidget.java:359)
	at com.guidewire.pl.web.value.ValueWidget.onUpdateModel(ValueWidget.java:339)
	at com.guidewire.pl.web.widget.Widget.updateModel_impl(Widget.java:416)
	at com.guidewire.pl.web.widget.Widget.updateModelForChildren(Widget.java:450)
	at com.guidewire.pl.web.widget.Widget.updateModel_impl(Widget.java:413)
	at com.guidewire.pl.web.widget.Widget.updateModelForChildren(Widget.java:450)
	at com.guidewire.pl.web.widget.Widget.updateModel_impl(Widget.java:413)
	at com.guidewire.pl.web.widget.Widget.updateModelForChildren(Widget.java:450)
	at com.guidewire.pl.web.widget.Widget.updateModel_impl(Widget.java:413)
	at com.guidewire.pl.web.widget.Widget.updateModelForChildren(Widget.java:450)
	at com.guidewire.pl.web.widget.Widget.updateModel_impl(Widget.java:413)
	at com.guidewire.pl.web.widget.Widget.updateModelForChildren(Widget.java:450)
	at com.guidewire.pl.web.widget.Widget.updateModel_impl(Widget.java:413)
	at com.guidewire.pl.web.widget.Widget.updateModel(Widget.java:408)
	at com.guidewire.pl.web.controller.lifecycle.UpdateModelStep.updateModelForLocation(UpdateModelStep.java:54)
	at com.guidewire.pl.web.controller.lifecycle.UpdateModelStep.execute(UpdateModelStep.java:34)
	at com.guidewire.pl.web.controller.lifecycle.LifecycleRequestHandler.runLifecycleSteps(LifecycleRequestHandler.java:150)
	at com.guidewire.pl.web.controller.lifecycle.LifecycleRequestHandler.handleRequest(LifecycleRequestHandler.java:117)
	at com.guidewire.pl.web.controller.WebControllerImpl$1.run(WebControllerImpl.java:174)
	at com.guidewire.pl.web.internaltools.profiler.WebProfiler.profilingBlock(WebProfiler.java:211)
	at com.guidewire.pl.web.controller.WebControllerImpl.processWithProfilingHouseKeeping(WebControllerImpl.java:170)
	at com.guidewire.pl.web.controller.WebControllerImpl.handleRequest(WebControllerImpl.java:142)
	at com.guidewire.pl.web.controller.WebServlet.handleRequest(WebServlet.java:185)
	at com.guidewire.pl.web.controller.WebServlet.doPost(WebServlet.java:127)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at com.guidewire.pl.web.controller.WebServlet.service(WebServlet.java:135)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at br.com.gcs.plugin.authentication.util.GCS_CustomTokenFilter.doFilter(GCS_CustomTokenFilter.java:41)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.guidewire.pl.web.controller.csrf.CSRFTokenFilter.doFilter(CSRFTokenFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:939)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

![image](https://user-images.githubusercontent.com/33718006/39412332-ec928804-4bf0-11e8-92f0-b1d7a28fe075.png)

Someone can help me please?

**Comment by abhijay94** [comment]
@douglasrezende Can you share your code for committing data to the database? This does not look like an issue with gosu-lang. You should raise this with Guidewire.
