### ISSUE TITLE
NullPointerException when gosu command is run on command prompt

### ISSUE THREAD

**Issue by CrisPana** [gosu-lang/gosu-lang#134]
I recently downloaded the new Gosu distribution and currently have jdk-10 set as my jdk but when I try to run Gosu on command prompt, it gives me the following error.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by gw.internal.gosu.parser.ClassCache (file:/C:/Users/Crischelle/gosu-1.14.7/lib/gosu-core-1.14.7.jar) to method java.lang.ClassLoader.getPackage(java.lang.String)
WARNING: Please consider reporting this to the maintainers of gw.internal.gosu.parser.ClassCache
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at gw.lang.reflect.ReflectUtil.findCallableMethod(ReflectUtil.java:189)
        at gw.lang.reflect.ReflectUtil.invokeMethod(ReflectUtil.java:111)
        at editor.util.Experiment.save(Experiment.java:233)
        at editor.util.Experiment.getOrMakeExperimentFile(Experiment.java:179)
        at editor.util.Experiment.load(Experiment.java:262)
        at editor.util.Experiment.<init>(Experiment.java:80)
        at editor.LabFrame.makeScratchExperiment(LabFrame.java:419)
        at editor.LabFrame.getUserFile(LabFrame.java:519)
        at editor.LabFrame.loadRecentExperiment(LabFrame.java:545)
        at editor.RunMe.lambda$launchEditor$0(RunMe.java:41)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I'm not entirely sure what the problem is. Can anybody help please? Thank you!

**Comment by DPUkyle** [comment]
Hi Crischelle. Sorry but Gosu requires Java 8.

Java 9/10 support will be coming, but sorry I can't promise a timeline yet.

**Comment by CrisPana** [comment]
Ah brilliant! Thank you!
