### ISSUE TITLE
Using structural type for two classes with the same name generates an exception.

### ISSUE THREAD

**Issue by dmazurki** [gosu-lang/gosu-lang#137]
I will explain this issue with an example.

Here I have one class in some package:

```
package scratch.pack_1

class Foo {
  var _x: int as X
}
```
Here there is another class with the same name in other package:
```
package scratch.pack_2

class Foo {
  var _x: int as X
}
```

I create the structural type to be able to pass both of those classes in my function:
```
package scratch

structure FooStructure {
  property get X(): int
}
```

This is the util function that uses my structure:
```
package scratch

class FooUtil {
  static function fooTest(foo: FooStructure) {
    print(foo.X)
  }
}
```

And here is the code that uses my function:
```
var fooPack1 = new scratch.pack_1.Foo() {:X = 5}
var fooPack2 = new scratch.pack_2.Foo() {:X = 6}

FooUtil.fooTest(fooPack1) // This will execute without errors.
FooUtil.fooTest(fooPack2) // Because of the bug, there will be an exception when invoking this function. 
```
Unfortunately, this code will produce an exception:

```
5
java.lang.RuntimeException: java.lang.IllegalArgumentException: argument type mismatch
	at gw.internal.gosu.ir.compiler.bytecode.expression.IRMethodCallExpressionCompiler.createNewProxy(IRMethodCallExpressionCompiler.java:168)
	at gw.internal.gosu.ir.compiler.bytecode.expression.IRMethodCallExpressionCompiler.constructProxy(IRMethodCallExpressionCompiler.java:122)
	at scratch.FooUtil.fooTest(FooUtil.gs:5)
	at scratch.RunMe.evaluate(RunMe.gsp:5)
	at gw.lang.Gosu.runWithType(Gosu.java:494)
	at gw.lang.Gosu.start(Gosu.java:115)
	at gw.lang.Gosu.main(Gosu.java:70)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gw.internal.gosu.ir.compiler.bytecode.expression.IRMethodCallExpressionCompiler.createNewProxy(IRMethodCallExpressionCompiler.java:165)
	... 6 more
Process finished with exit code 0
```

From my quick investigation, the proxy object that is generated for the second class is invalid (in the constructor it accepts the object of type **scratch.pack_1.Foo**  instead of **scratch.pack_2.Foo**).

**Comment by DPUkyle** [comment]
Thank you for the report. Please share what version of the Gosu libraries
you are using.

- Kyle

**Comment by dmazurki** [comment]
This is gosu-1.14.7.
