### ISSUE TITLE
GenericSignatureFormatError when getting generic info from reflection

### ISSUE THREAD

**Issue by JakubJakobczyk** [gosu-lang/gosu-lang#152]
**Steps to reproduce this error:**
1. Create class with method that has array as parameter and returning parameterized object, e.g.
```
class Clazz<T> {
  function fun(arr : int[]) : List<Integer> {
    return null  
  }
}
```
2. Try to retrieve information from reflection with following code:
```
var c = new Clazz<Integer>()
for (var m in c.Class.getMethods()) {
    print(m.getName())
    print(m.getGenericReturnType())
  }
```
3. The result is following exception:

> fun
java.lang.reflect.GenericSignatureFormatError: Signature Parse error: expected ')'
	Remaining input: ;)Ljava/util/List<Ljava/lang/Integer;>;
	at sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
	at sun.reflect.generics.parser.SignatureParser.parseFormalParameters(SignatureParser.java:586)
	at sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:576)
	at sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
	at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:55)
	at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
	at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
	at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
	at sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:51)
	at sun.reflect.generics.repository.MethodRepository.<init>(MethodRepository.java:46)
	at sun.reflect.generics.repository.MethodRepository.make(MethodRepository.java:59)
	at java.lang.reflect.Method.getGenericInfo(Method.java:102)
	at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
	at _nopackage_.GosuScratchpad.evaluate(Gosu Scratchpad.gsp:6)
	at gw.lang.Gosu.runWithFile(Gosu.java:436)
	at gw.lang.Gosu.start(Gosu.java:113)
	at gw.lang.Gosu.main(Gosu.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:46)

**Additional information**
When trying to use javap program from JDK, I get following result:

> Compiled from "Clazz.gs"
public class tst.Clazz<T> implements gw.lang.reflect.gs.IGosuObject {
  final gw.lang.reflect.LazyTypeResolver typeparam$T;
  static {};
  public tst.Clazz(gw.lang.reflect.LazyTypeResolver);
Error: A serious internal error has occurred: java.lang.IllegalStateException: ([I!;!)Ljava/util/List<Ljava/lang/Integer;>;
Please file a bug report, and include the following information:
java.lang.IllegalStateException: ([I!;!)Ljava/util/List<Ljava/lang/Integer;>;
        at com.sun.tools.classfile.Signature.parseTypeSignature(Signature.java:180)
        at com.sun.tools.classfile.Signature.parseTypeSignatures(Signature.java:188)
        at com.sun.tools.classfile.Signature.parse(Signature.java:93)
        at com.sun.tools.classfile.Signature.getType(Signature.java:48)
        at com.sun.tools.javap.ClassWriter.writeMethod(ClassWriter.java:437)
        at com.sun.tools.javap.ClassWriter.writeMethods(ClassWriter.java:412)
        at com.sun.tools.javap.ClassWriter.write(ClassWriter.java:217)
        at com.sun.tools.javap.JavapTask.write(JavapTask.java:784)
        at com.sun.tools.javap.JavapTask.writeClass(JavapTask.java:606)
        at com.sun.tools.javap.JavapTask.run(JavapTask.java:560)
        at com.sun.tools.javap.JavapTask.run(JavapTask.java:423)
        at com.sun.tools.javap.Main.main(Main.java:46)

Further investigation shown that the problem is with array types in function argument - compiler for each array dimension inserts ';' into bytecode at the end of argument type. So `int[][][]` as a argument will result with '[I;;;' in the bytecode.The problem also occurs with following arguments: `arg : Collection<Integer[]>` and `arg : Collection<Collection<Integer[][][]>>`

**Comment by JakubJakobczyk** [comment]
Checked. The problem was in gosu 1.13.9. In 1.14.10 this problem not occures
