### ISSUE TITLE
gosu wont start on virtual machine

### ISSUE THREAD

**Issue by maciejjankowski** [gosu-lang/gosu-lang#81]
I wanted to try gosu on ubuntu 14.04 (no X)
and all I got was this exception when running ./gosu:
````
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at editor.BasicGosuEditor.<init>(BasicGosuEditor.java:25)
        at editor.BasicGosuEditor.create(BasicGosuEditor.java:175)
        at editor.RunMe.lambda$launchEditor$0(RunMe.java:45)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

````

**Comment by DPUkyle** [comment]
Hi, and sorry for the delayed response.

Gosu doesn't have a REPL, rather you'd want to provide a *.gsp containing code to run, or an inline script on the command line. For example:

```
$ bin/gosu -e 'print(\"Hello world!\")'
Hello world!
```

And you can see the default help by running `$ bin/gosu /?`
```
Gosu version: 1.13.8
Usage:
    gosu [-checkedArithmetic] [-classpath 'entry1,entry2...'] program.gsp [args...]
    gosu [-checkedArithmetic] [-classpath 'entry1,entry2...'] -e 'inline script' [args...]
```

Running `$ ./gosu` without arguments launches our simple editor called Gosu Lab, which is why AWT blew up when invoked from a terminal.
