### ISSUE TITLE
error when trying to open editor in latest distribution( i am using linux mint 17 and java 8)

### ISSUE THREAD

**Issue by hazourano** [gosu-lang/gosu-lang#87]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at editor.tabpane.ContentContainer$ContentInnerBorder.initInsets(ContentContainer.java:109)
    at editor.tabpane.ContentContainer$ContentInnerBorder.getBorderInsets(ContentContainer.java:105)
    at javax.swing.JComponent.setBorder(JComponent.java:1799)
    at editor.tabpane.ContentContainer.configUi(ContentContainer.java:23)
    at editor.tabpane.ContentContainer.<init>(ContentContainer.java:19)
    at editor.tabpane.TabPane.configUi(TabPane.java:283)
    at editor.tabpane.TabPane.<init>(TabPane.java:91)
    at editor.tabpane.TabPane.<init>(TabPane.java:80)
    at editor.GosuPanel.configUI(GosuPanel.java:121)
    at editor.GosuPanel.<init>(GosuPanel.java:108)
    at editor.BasicGosuEditor.configUI(BasicGosuEditor.java:89)
    at editor.BasicGosuEditor.<init>(BasicGosuEditor.java:26)
    at editor.BasicGosuEditor.create(BasicGosuEditor.java:175)
    at editor.RunMe.lambda$launchEditor$0(RunMe.java:45)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by hazourano** [comment]
why do i need to run it as sudo?

**Comment by DPUkyle** [comment]
Hmm this is strange; sudo should not be required. The editor does create and store project metadata in ~/.GosuLab but it does not need root permissions for anything. We'll investigate the ST.

**Comment by DPUkyle** [comment]
Could not reproduce on Ubuntu 16.04 with latest [1.14.4](http://search.maven.org/remotecontent?filepath=org/gosu-lang/gosu/gosu/1.14.4/gosu-1.14.4-full.zip) distribution. Please feel free to reopen if the problem persists.
