### ISSUE TITLE
Getting 'NullPointerException' error while running 'gosu' command for Gosu lab

### ISSUE THREAD

**Issue by nagarajugit29** [gosu-lang/gosu-lang#88]
Hi Team,

I have downloaded **gosu-1.14.1-full**  distribution and using this in my windows system. After using some days, now I am getting the below error/exception when I am trying to load Gosu Lab  using 'gosu' exe file. Please check and let me know the reason why it was failed to load.

The below is the detailed error.

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.NullPointerException
        at editor.util.EditorUtilities.loadRecentExperiment(EditorUtilities.java:814)
        at editor.RunMe.lambda$launchEditor$0(RunMe.java:46)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(Unknown Source)
        at editor.util.EditorUtilities.loadRecentExperiment(EditorUtilities.java:810)
        ... 15 more

**Comment by DPUkyle** [comment]
This should be corrected by subsequent releases. Please try [1.14.4](http://search.maven.org/remotecontent?filepath=org/gosu-lang/gosu/gosu/1.14.4/gosu-1.14.4-full.zip) and feel free to reopen this issue if the problem persists.
