### ISSUE TITLE
Incorrect annotation handling while generating 'proxy' class

### ISSUE THREAD

**Issue by seroperson** [gosu-lang/gosu-lang#91]
Hello there. gosuc fails with the similar stacktrace:

```
java.lang.RuntimeException: java.lang.ClassCastException: gw.internal.gosu.parser.AsmMethodJavaClassMethod cannot be cast to gw.lang.reflect.java.IJavaClassType
        at gw.internal.gosu.parser.GosuClassProxyFactory$LazyStringSourceFileHandle.getSource(GosuClassProxyFactory.java:229)
        at gw.internal.gosu.parser.GosuClass.makeParserForPhase(GosuClass.java:2577)
        at gw.internal.gosu.parser.GosuClass.compileHeaderIfNeeded(GosuClass.java:1835)
        at gw.internal.gosu.parser.GosuClass.getSuperClass(GosuClass.java:2056)
        at gw.internal.gosu.parser.GosuClass_Proxy.getSuperClass(gw.internal.gosu.parser.GosuClass_Proxy:2)
        at gw.internal.gosu.parser.GosuClass.getTypeInfo(GosuClass.java:981)
        at gw.internal.gosu.parser.GosuClass.getTypeInfo(GosuClass.java:96)
        at gw.internal.gosu.parser.GosuClass_Proxy.getTypeInfo(gw.internal.gosu.parser.GosuClass_Proxy:2)
        at gw.internal.gosu.parser.GosuClass.getTypeInfo(GosuClass.java:983)
        at gw.internal.gosu.parser.GosuClass.getTypeInfo(GosuClass.java:96)
        at gw.internal.gosu.parser.GosuClass_Proxy.getTypeInfo(gw.internal.gosu.parser.GosuClass_Proxy:2)
        at gw.lang.gosuc.simple.GosuCompiler.isCompilable(GosuCompiler.java:94)
        at gw.lang.gosuc.simple.GosuCompiler.compile(GosuCompiler.java:58)
        at gw.lang.gosuc.cli.CommandLineCompiler.execute(CommandLineCompiler.java:66)
        at gw.lang.gosuc.cli.CommandLineCompiler.main(CommandLineCompiler.java:27)
  Caused by: java.lang.ClassCastException: gw.internal.gosu.parser.AsmMethodJavaClassMethod cannot be cast to gw.lang.reflect.java.IJavaClassType
        at gw.internal.gosu.parser.java.classinfo.AsmClassAnnotationInfo.makeArray(AsmClassAnnotationInfo.java:67)
        at gw.internal.gosu.parser.java.classinfo.AsmClassAnnotationInfo.normalizeValue(AsmClassAnnotationInfo.java:58)
        at gw.internal.gosu.parser.java.classinfo.AsmClassAnnotationInfo.getFieldValue(AsmClassAnnotationInfo.java:53)
        at gw.internal.gosu.parser.GosuClassProxyFactory.makeAnnotationSource(GosuClassProxyFactory.java:361)
        at gw.internal.gosu.parser.GosuClassProxyFactory.addAnnotations(GosuClassProxyFactory.java:342)
        at gw.internal.gosu.parser.GosuClassProxyFactory.buildModifiers(GosuClassProxyFactory.java:975)
        at gw.internal.gosu.parser.GosuClassProxyFactory.genMemberMethod(GosuClassProxyFactory.java:613)
        at gw.internal.gosu.parser.GosuClassProxyFactory.genMethodImpl(GosuClassProxyFactory.java:535)
        at gw.internal.gosu.parser.GosuClassProxyFactory.genClassImpl(GosuClassProxyFactory.java:294)
        at gw.internal.gosu.parser.GosuClassProxyFactory.genJavaClassProxy(GosuClassProxyFactory.java:253)
        at gw.internal.gosu.parser.GosuClassProxyFactory.access$100(GosuClassProxyFactory.java:42)
        at gw.internal.gosu.parser.GosuClassProxyFactory$2.call(GosuClassProxyFactory.java:198)
        at gw.internal.gosu.parser.GosuClassProxyFactory$2.call(GosuClassProxyFactory.java:193)
        at gw.internal.gosu.parser.GosuClassProxyFactory$LazyStringSourceFileHandle.getSource(GosuClassProxyFactory.java:225)
        ... 14 more
```

If there the following conditions are met:

1. Some annotation with any array field.
2. Java class with method/field/constructor that annotated with the annotation.
3. Gosu class that extends the java class and overrides any it's method.

[Here](https://bitbucket.org/seroperson/gosu-fail-example) is sample project where you can make it fail.

I dived into it and as far as I can see (of course, maybe I wrong), the fix is pretty simple and I can send you PR with commit. Just feel the need to create issue firstly.

**Comment by rsmckinney** [comment]
Thanks, seroperson, for reporting this!
