### ISSUE TITLE
JsonListType.getName() throws when given an empty array

### ISSUE THREAD

**Issue by DPUkyle** [gosu-lang/gosu-lang#94]
Given the sample program:
```
var input = "{\"arrayOfSomething\": []}"
var output = gw.lang.reflect.json.Json.fromJson(input).toStructure("meh")
```

Will throw:
```
Exception in thread "main" java.lang.NullPointerException
	at gw.lang.reflect.json.JsonListType.getName(JsonListType.java:22)
	at gw.lang.reflect.json.JsonStructureType.render(JsonStructureType.java:73)
	at gw.lang.reflect.json.Json.makeStructureTypes(Json.java:82)
	at gw.lang.enhancements.CoreBindingsEnhancement.toStructure(CoreBindingsEnhancement.gsx:21)
```

Since `arrayOfSomething` contains no sample elements, we cannot accurately infer the component type in JsonListType, hence the NPE.

@rsmckinney and I discussed this and maybe we will default to `List<Dynamic>` in this scenario.

**Comment by DPUkyle** [comment]
2bbfb45eec
